services:
  app:
    image: python-test:local
    build: .
    ports:
      - "8080:8040"
    environment:
      NUITKA: "0"
      WORKERS: "1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040/create"]
      start_period: 15s
      start_interval: 1s
      interval: 99m


  benchmarker:
    image: blazemeter/taurus:1.16.31
    volumes:
      - ./taurus-tests:/bzt-configs
    command: benchmark.yaml
    depends_on:
      app:
        condition: service_healthy
    restart: on-failure
