services:
  app:
    image: python-django-test:local
    init: true
    build: .
    ports:
      - "8080:8040"
    environment:
      WORKERS: "1"  # set to 1 or 4
      POSTGRES: "1"  # set to 0 or 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040/create"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  benchmarker:
    image: blazemeter/taurus:1.16.31
    volumes:
      - ./taurus-tests:/bzt-configs
    command: benchmark.yaml
    depends_on:
      app:
        condition: service_healthy
    restart: on-failure
