services:
  app:
    image: pocketbaset-test:local
    build: .
    ports:
      - "8080:8040"
    environment:
      GOMAXPROCS: "1"  # set to 1 or 4 in the benchmarks
#      GOMEMLIMIT: "200MiB"  # uncomment to set a soft-limit on memory usage for the Go GC


  benchmarker:
    image: blazemeter/taurus:1.16.31
    volumes:
      - ./taurus-tests:/bzt-configs
    command: benchmark.yaml
    depends_on:
      - app
    restart: on-failure
